import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  params: {
    locale: string,
  },
  children: React.ReactNode;
};

export default async function RootLayout({ params, children }: LayoutProps) {

  // i18n
  const { locale } = params;

  return (
    <html lang={locale}>
      <body className={inter.className}>
        {/* <DebugBar /> */}
        <header className="p-4">
          <div className="p-4 bg-neutral-950">
            <p>RootLayout locale: {locale}</p>
          </div>
        </header>
        {/* Page */}
        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
}